// Code generated by mockery v2.42.1. DO NOT EDIT.

package controller

import (
	context "context"

	condition "github.com/metal-toolbox/rivets/condition"

	mock "github.com/stretchr/testify/mock"
)

// MockConditionHandler is an autogenerated mock type for the ConditionHandler type
type MockConditionHandler struct {
	mock.Mock
}

type MockConditionHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConditionHandler) EXPECT() *MockConditionHandler_Expecter {
	return &MockConditionHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: ctx, _a1, publisher
func (_m *MockConditionHandler) Handle(ctx context.Context, _a1 *condition.Condition, publisher ConditionStatusPublisher) error {
	ret := _m.Called(ctx, _a1, publisher)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *condition.Condition, ConditionStatusPublisher) error); ok {
		r0 = rf(ctx, _a1, publisher)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConditionHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockConditionHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *condition.Condition
//   - publisher ConditionStatusPublisher
func (_e *MockConditionHandler_Expecter) Handle(ctx interface{}, _a1 interface{}, publisher interface{}) *MockConditionHandler_Handle_Call {
	return &MockConditionHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, _a1, publisher)}
}

func (_c *MockConditionHandler_Handle_Call) Run(run func(ctx context.Context, _a1 *condition.Condition, publisher ConditionStatusPublisher)) *MockConditionHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*condition.Condition), args[2].(ConditionStatusPublisher))
	})
	return _c
}

func (_c *MockConditionHandler_Handle_Call) Return(_a0 error) *MockConditionHandler_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConditionHandler_Handle_Call) RunAndReturn(run func(context.Context, *condition.Condition, ConditionStatusPublisher) error) *MockConditionHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConditionHandler creates a new instance of MockConditionHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConditionHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConditionHandler {
	mock := &MockConditionHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
