name: lint and test
on: [pull_request, push]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    - name: Checkout code
      uses: actions/checkout@v3
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: --config .golangci.yml --timeout 2m
        version: v1.55.2
    - name: Test
      run: go test ./...
  build:
    runs-on: ubuntu-latest
    needs: [lint-test]
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Checkout code
        uses: actions/checkout@v3
